services:
  tmw-bot:
    image: discord-jouzu-bot
    environment:
      - TOKEN
      - AUTHORIZED_USERS
      - DEBUG_USER
      - COMMAND_PREFIX
      - PATH_TO_DB
      - TMDB_API_KEY
    volumes:
      - ./data:/app/data
    restart: unless-stopped
