rank_structure:
  1297383002610995272:
    - name: "Student"
      combination_rank: false
      font: "Eishiikaisho"
      font_size: 100
      rank_to_get: 1297383002694746173
      foreground: "#f173ff"
      effect: null
      time_limit: 16000
      decks:
        - "jpdb1k"
      deck_range:
        - 1
        - 300
      score_limit: 25
      max_missed: 10
      command: f"k!quiz jpdb1k(1-300) 25 hardcore nd mmq=10 dauq=1 font=5 color=#f173ff size=100"

    - name: "Trainee"
      combination_rank: false
      font: "Eishiikaisho"
      font_size: 100
      rank_to_get: 1297383002694746174
      foreground: "#f173ff"
      effect: null
      time_limit: 16000
      decks:
        - "jpdb1k"
      deck_range: null
      score_limit: 50
      max_missed: 10
      command: "k!quiz jpdb1k 50 hardcore nd mmq=10 dauq=1 font=5 color=#f173ff size=100"

    - name: "Debut Idol"
      combination_rank: false
      font: "Eishiikaisho"
      font_size: 100
      rank_to_get: 1297383002694746175
      foreground: "#f173ff"
      effect: "antiocr"
      time_limit: 16000
      decks:
        - "jpdb2_5k"
        - "jpdb5k"
      deck_range: null
      score_limit: 50
      max_missed: 10
      command: "k!quiz jpdb2_5k+jpdb5k 50 hardcore nd mmq=10 dauq=1 font=5 color=#f173ff size=100 effect=antiocr"

    - name: "Major Idol"
      combination_rank: false
      font: "Eishiikaisho"
      font_size: 100
      rank_to_get: 1297383002694746176
      foreground: "#f173ff"
      effect: "antiocr"
      time_limit: 16000
      decks:
        - "jpdb5k"
        - "jpdb10k"
      deck_range: null
      score_limit: 50
      max_missed: 10
      command: "k!quiz jpdb5k+jpdb10k 50 hardcore nd mmq=10 dauq=1 font=5 color=#f173ff size=100 effect=antiocr"

    - name: "Prima Idol Vocab"
      combination_rank: false
      font: "Eishiikaisho"
      font_size: 100
      rank_to_get: null
      foreground: "#f173ff"
      effect: "antiocr"
      time_limit: 16000
      decks:
        - "jpdb10k"
        - "jpdb15k"
      deck_range: null
      score_limit: 50
      max_missed: 10
      command: "k!quiz jpdb10k+jpdb15k 50 hardcore nd mmq=10 dauq=1 font=5 color=#f173ff size=100 effect=antiocr"

    - name: "Divine Idol Vocab"
      combination_rank: false
      font: "Eishiikaisho"
      font_size: 100
      rank_to_get: null
      foreground: "#f173ff"
      effect: "antiocr"
      time_limit: 16000
      decks:
        - "jpdb15k"
        - "jpdb20k"
      deck_range: null
      score_limit: 50
      max_missed: 10
      command: "k!quiz jpdb15k+jpdb20k 50 hardcore nd mmq=10 dauq=1 font=5 color=#f173ff size=100 effect=antiocr"

    - name: "Eternal Idol Vocab"
      combination_rank: false
      font: "Eishiikaisho"
      font_size: 100
      rank_to_get: null
      foreground: "#f173ff"
      effect: "antiocr"
      time_limit: 16000
      decks:
        - "jpdb20k"
        - "jpdb25k"
      deck_range: null
      score_limit: 50
      max_missed: 10
      command: "k!quiz jpdb20k+jpdb25k 50 hardcore nd mmq=10 dauq=1 font=5 color=#f173ff size=100 effect=antiocr"

    - name: "GN2"
      combination_rank: false
      font: null
      font_size: null
      rank_to_get: null
      foreground: null
      effect: null
      time_limit: 16000
      decks:
        - "gn2"
      deck_range: null
      score_limit: 20
      max_missed: 4
      command: "k!quiz gn2 nd 20 mmq=4"

    - name: "GN1"
      combination_rank: false
      font: null
      font_size: null
      rank_to_get: null
      foreground: null
      effect: null
      time_limit: 16000
      decks:
        - "gn1"
      deck_range: null
      score_limit: 20
      max_missed: 4
      command: "k!quiz gn1 nd 20 mmq=4"

    - name: "Prima Idol"
      combination_rank: true
      decks: null
      quizzes_required: ["GN2", "Prima Idol Vocab"]
      rank_to_get: 1297383002694746177

    - name: "Divine Idol"
      combination_rank: true
      decks: null
      quizzes_required: ["GN1", "Divine Idol Vocab"]
      rank_to_get: 1297383002694746178

    - name: "Eternal Idol"
      combination_rank: true
      decks: null
      quizzes_required: ["GN1", "Eternal Idol Vocab"]
      rank_to_get: 1297383002694746179

settings:
  1297383002610995272:
    valid_levelup_channels:
      - 1297383004817330210 # Quiz
      - 1297383004817330211 # Quiz-2
      - 1297383004817330212 # Quiz-3
      - 1297383004817330213 # Quiz-4
      - 1297383004817330214 # Quiz-5
    restricted_quiz_names:
      - "jpdb1k"
      - "jpdb2_5k"
      - "jpdb5k"
      - "jpdb10k"
      - "jpdb15k"
      - "jpdb20k"
      - "jpdb25k"
    announce_channel: 1297383003479081019
